NextechSystems/selectapidocspub

source/includes/_patient.md

NX-109675 - update the patient resource documentation to include the fields and an example

---

source/includes/_appointment.md
source/includes/_authentication.md
source/includes/_introduction.md
source/includes/_patient.md

Updated docs to use the production endpoint

---

source/includes/_gettingstarted.md

Updated the tenant name for authentication

---

source/includes/_patient.md

Fixed typo in Patient examples

---

source/includes/_gettingstarted.md

Added Authorization details to the Using Postman section

---

source/includes/_appointment.md

@dustinlange 
@ChrisHaagNXT 
@bobcardillo
@jsmet

NX-110091 - updated the documentation for new appt search functionality

---

source/includes/_patient.md

@ChrisHaagNXT 
@dustinlange 
@bobcardillo

NX-110376 - Documentation

---

source/includes/_appointment.md

NX-110776 - Added support for searching by appointment created date

---

source/includes/_appointment.md
source/includes/_location.md
source/includes/_patient.md
source/index.html.md

NX-110773 - Added documentation for Location resource

---

source/includes/_introduction.md

Updated functionality section

---

source/includes/_appointment.md
source/includes/_patient.md

Added Practice versions to search parameters and available fields

---

source/includes/_patient.md

@ChrisHaagNXT
@dustinlange
@BobCardillo
@JCamachoNXT
@jsmet
@JakeDriscoll
@VinnieMaida
@hemangshahnxt

NX-111245 - Code: Document Category

---

source/includes/_practitioner.md
source/index.html.md

NX-111157 - added documentation for practitioner

---

source/includes/_gettingstarted.md

Removed references to client secret; Moved the 'Using Postman' section below 'Authentication'

---

source/includes/_appointment.md
source/includes/_appointmenttype.md
source/index.html.md

@JakeDriscoll 
@JGruberNXT 
@dustinlange 
Documentation pull request.

NX-111812 - Add Appointment Type changes

---

source/includes/_appointment.md
source/includes/_appointmentpurpose.md
source/includes/_appointmenttype.md

@JGruberNXT 
@JakeDriscoll 
@BobCardillo 
@dustinlange

NX-112077 - Appt purpose changes

---

source/includes/_patient.md

NX-112229-Payment Extension Rework

---

source/index.html.md

@dustinlange 
Just getting the index up to date

NX-112077 -  update index to have resource endpoint

---

source/includes/_introduction.md
source/includes/_slot.md
source/index.html.md

@BobCardillo 
@JCamachoNXT 
@JakeDriscoll 
@hemangshahnxt 
@jsmet 
@VinnieMaida 
@dustinlange

NX-112590 - documentation

---

source/includes/_slot.md

@dustinlange 
@BobCardillo 
@JCamachoNXT 
@JakeDriscoll

NX-112881 - fixed the examples

---

source/includes/_appointment.md

@VinnieMaida 
@BobCardillo 
@jsmet 
@JCamachoNXT 
@JakeDriscoll 
@hemangshahnxt 
@dustinlange

AR-102 - documentation for book

---

source/includes/_appointment.md
source/includes/_slot.md

@BobCardillo 
@VinnieMaida 
@JakeDriscoll 
@jsmet 
@JCamachoNXT 
@hemangshahnxt

Held documentation

---

source/includes/_slot.md

AR-266 - fixed typo

---

source/includes/_patient.md

@jsmet 
@JakeDriscoll 
@JCamachoNXT 
@BobCardillo 
@VinnieMaida 
@hemangshahnxt

AR-1493 - documentation for create patient

---

source/includes/_patient.md

@JakeDriscoll 
@BobCardillo 
@jsmet 
@VinnieMaida 
@JCamachoNXT 
@hemangshahnxt

AR-1610 - documentation for additional patient fields

---

source/includes/_patient.md

@BobCardillo 
@JakeDriscoll 
@JCamachoNXT 
@jsmet 
@VinnieMaida 
@hemangshahnxt

AR-1634 - documentation for publish to portal
